const env = process.env;

const CLOUDNERY_API_NAME = env.CLOUDNERY_API_NAME || "CLOUDNERY_API_NAME_DEFAULT";
const CLOUDNERY_API_KEY = env.CLOUDNERY_API_KEY || "CLOUDNERY_API_KEY_DEFAULT";
const CLOUDNERY_API_SECRET = env.CLOUDNERY_API_SECRET || "CLOUDNERY_API_SECRET_DEFAULT";

const ACCESS_SECRET_KEY = env.ACCESS_SECRET_KEY || "ACCESS_SECRET_KEY_DEFAULT";
const REFRESH_SECRET_KEY = env.REFRESH_SECRET_KEY || "REFRESH_SECRET_KEY_DEFAULT";

const DB_HOST = env.DB_HOST || "DB_HOST_DEFAULT";
const PORT = env.PORT || 5000;
const FRONTEND_URL = env.FRONTEND_URL || "FRONTEND_URL_DEFAULT";

//For google autanticate
const GOOGLE_ACCESS_SECRET_KEY = env.GOOGLE_ACCESS_SECRET_KEY || "GOOGLE_ACCESS_SECRET_KEY_DEFAULT";
const GOOGLE_REFRESH_SECRET_KEY = env.GOOGLE_REFRESH_SECRET_KEY || "GOOGLE_REFRESH_SECRET_KEY_DEFAULT";

module.exports = {
	CLOUDNERY_API_NAME,
	CLOUDNERY_API_KEY,
	CLOUDNERY_API_SECRET,
	ACCESS_SECRET_KEY,
	REFRESH_SECRET_KEY,
	DB_HOST,
	PORT,
	FRONTEND_URL,
	GOOGLE_ACCESS_SECRET_KEY,
	GOOGLE_REFRESH_SECRET_KEY,
};
